# Generated by Django 5.0.3 on 2024-03-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='profile_picture',
            field=models.FileField(null=True, upload_to='static\\profile_pictures'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='profilename',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
