# Generated by Django 5.0.3 on 2024-03-14 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_questionsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsmodel',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
