# Generated by Django 5.0.3 on 2024-03-14 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_questionsmodel_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_id', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=30)),
                ('question', models.TextField(null=True)),
                ('time', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'AnswersModel',
            },
        ),
        migrations.RemoveField(
            model_name='questionsmodel',
            name='answers',
        ),
    ]
