# Generated by Django 5.0.3 on 2024-03-14 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_answersmodel_remove_questionsmodel_answers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answersmodel',
            old_name='question',
            new_name='answers',
        ),
    ]
