# Generated by Django 5.0.3 on 2024-03-14 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_question_answersmodel_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsmodel',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
