# Generated by Django 5.0.3 on 2024-03-15 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_q_id_answersmodel_qid'),
    ]

    operations = [
        migrations.AddField(
            model_name='answersmodel',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
