# Generated by Django 5.0.2 on 2024-03-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_answersmodel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='followers',
            field=models.IntegerField(default=0),
        ),
    ]
