# Generated by Django 5.0.2 on 2024-03-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_usermodel_followers'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('email', models.EmailField(max_length=254, null=True)),
                ('follow', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'FollowModel',
            },
        ),
    ]
